### ISSUE TITLE
Question about the package version

### ISSUE THREAD

**Issue by mostly-harmless-earth** [CederGroupHub/synthesis-action-retriever#1]
when I test the synthesis-action-retriever, i got the error like this:
(fsl) D:\LFSS\synthesis-action-retriever>python
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 15:53:35) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from synthesis_action_retriever.synthesis_action_retriever import SynthActionRetriever
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\LFSS\synthesis-action-retriever\synthesis_action_retriever\synthesis_action_retriever.py", line 5, in <module>
    from gensim.models import Word2Vec
  File "D:\aconcon\envs\fsl\lib\site-packages\gensim-3.8.0-py3.8-win-amd64.egg\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "D:\aconcon\envs\fsl\lib\site-packages\gensim-3.8.0-py3.8-win-amd64.egg\gensim\corpora\__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "D:\aconcon\envs\fsl\lib\site-packages\gensim-3.8.0-py3.8-win-amd64.egg\gensim\corpora\indexedcorpus.py", line 15, in <module>
    from gensim import interfaces, utils
  File "D:\aconcon\envs\fsl\lib\site-packages\gensim-3.8.0-py3.8-win-amd64.egg\gensim\interfaces.py", line 21, in <module>
    from gensim import utils, matutils
  File "D:\aconcon\envs\fsl\lib\site-packages\gensim-3.8.0-py3.8-win-amd64.egg\gensim\matutils.py", line 1104, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "__init__.pxd", line 242, in init gensim._matutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
>>>

i think it might be the problem about the numpy, here is my list:
 Package                 Version
----------------------- ----------
absl-py                 1.4.0
astunparse              1.6.3
blis                    0.7.9
cachetools              5.3.0
catalogue               2.0.8
certifi                 2022.12.7
charset-normalizer      3.1.0
click                   8.1.3
colorama                0.4.6
confection              0.0.4
cymem                   2.0.7
gast                    0.3.3
gensim                  3.8.0
google-auth             2.17.2
google-auth-oauthlib    1.0.0
google-pasta            0.2.0
grpcio                  1.54.0rc1
h5py                    2.10.0
idna                    3.4
importlib-metadata      6.1.0
Jinja2                  3.1.2
Keras-Preprocessing     1.1.2
langcodes               3.3.0
Markdown                3.4.3
MarkupSafe              2.1.2
murmurhash              1.0.9
numpy                   1.16.0
oauthlib                3.2.2
operations-extractor    4.0.0
opt-einsum              3.3.0
packaging               23.0
pathy                   0.10.1
pip                     23.0.1
preshed                 3.0.8
protobuf                4.22.1
pyasn1                  0.5.0rc2
pyasn1-modules          0.3.0rc1
pydantic                1.10.7
regex                   2023.3.23
requests                2.28.2
requests-oauthlib       1.3.1
rsa                     4.9
scipy                   1.4.1
setuptools              67.6.1
six                     1.16.0
smart-open              6.3.0
spacy                   4.0.0.dev0
spacy-legacy            3.0.12
spacy-loggers           1.0.4
srsly                   2.4.6
tensorboard             2.12.1
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
tensorflow              2.3.0
tensorflow-estimator    2.3.0
termcolor               2.2.0
thinc                   9.0.0.dev3
tqdm                    4.65.0
typer                   0.7.0
typing_extensions       4.5.0
urllib3                 1.26.15
wasabi                  1.1.1
Werkzeug                2.2.3
wheel                   0.40.0
wrapt                   1.15.0
zipp                    3.15.0

I am wondering what version is correct for the installation. Thank you so much.

**Comment by kevcruse96** [comment]
Hi there, many apologies for never responding to this! Yes, this seems to be related to the numpy version... numpy==1.18.5 works for my instance.
